server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: backend
              uri: http://localhost:9000
              predicates:
                - Path=/backend/**

            - id: frontend
              uri: http://localhost:5173
              predicates:
                - Path=/**
