server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    web: DEBUG

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: backend
              uri: http://localhost:9000
              predicates:
                - Path=/backend/**
              filters:
                - RewritePath=/backend/(?<segment>.*), /$\{segment}
            - id: frontend
              uri: http://localhost:5173/
              predicates:
                - Path=/**