server:
  port: 9000

#logging:
#  level:
#    web: debug

spring:
  application:
    name: backend

  r2dbc:
    url: r2dbc:h2:mem:///sampleDb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization:
      enabled: true

  sql:
    init:
      mode: always
